site_name: 'Building Detections in AWS'
copyright: 'Â©2023 Ryan Nicholson | Blue Mountain Cyber, LLC'
site_description: 'Building Detections in AWS'
site_author: 'Ryan Nicholson'
extra:
  version: '2023-03-17'

INHERIT: ./base_config.yml

nav:
  - Home: 'index.md'
  - Labs:
    - 'Exercise 1: Infrastructure Deployment': 'exercises/exercise1.md'
    - 'Exercise 2: Setting Up Logging': 'exercises/exercise2.md'
    - 'Exercise 3: Attacking the Cloud Account': 'exercises/exercise3.md'
    - 'Exercise 4: Detecting the Attack': 'exercises/exercise4.md'
    - 'Exercise 5: Building an Automated Detection': 'exercises/exercise5.md'
    - 'Exercise 6: Tearing Down Resources': 'exercises/exercise6.md'
